### ISSUE TITLE
Goto definition issue

### ISSUE THREAD

**Issue by khelifaadm** [smallp/vscode-ci#1]
error messgae displayed when trying to access $this->users->method()
messsage:
**Unable to open 'Users.php': File not found (\\\c:\wamp64 \www\project\application\models\Users.php).**

**Comment by smallp** [comment]
So what's your file name? Is the uri of users model c:\wamp64 \www\project\application\models\Users.php?

**Comment by smallp** [comment]
Get the point. The path is different between windows and Linux. As I'm developing it in Linux, it can not work well in windows. I'll fix it later.

**Comment by smallp** [comment]
#d3f2749 done.

**Comment by smallp** [comment]
#d3f27499a6d83d6a2b27c4ae36934a0a63291618 done.

**Comment by khelifaadm** [comment]
the problem still remaining
i tweak it like by:
loader.js => function _path2uri
 return encodeURI(`file:${path}`);
-------------------------
system windows 10
thank a lot for what you are doing

**Comment by smallp** [comment]
Ok, I see. I'll fix it in next version.
