### ISSUE TITLE
Code Completion not work after update 1.18.0 Windows

### ISSUE THREAD

**Issue by maxdimaz** [smallp/vscode-ci#10]
Hi i got issue yesterday this plugin work perfectly after today i got notification to install update and this plugin not work anymore on my machine Windows 10. 

I was trying to downgrade to VSC 1.17.1 and still no luck, uninstall all plugin and reinstall this one still not work.

Thanks

**Comment by smallp** [comment]
Please see my last issue. It can not read the correct file in windows due to the different file system between windows and Linux. I'll fix it in next 2 days.
