### ISSUE TITLE
Libraries are not autoloaded

### ISSUE THREAD

**Issue by mehdibo** [smallp/vscode-ci#11]
I understand from the extension's details that the libraries are parsed if you load them using
`$this->load->library()`.
You said 

> Add a issue if you believe that is nesessary.

Well I do, because some of my libraries are autoloaded which mean the extension doesn't detect them, any chance of adding an option for libraries?

**Comment by smallp** [comment]
Got it. I'll add it to config in next version.

**Comment by mehdibo** [comment]
Thanks!

**Comment by fgv13** [comment]
Great job! Could you consider for this issue and for the related #14, the autoload using alias?
