### ISSUE TITLE
Error in DB methods

### ISSUE THREAD

**Issue by rquispeq** [smallp/vscode-ci#12]
I read that this extension work only with db variable, thats ok for me, i work with that variable too, but still giveme this error while i hover on a db methods like get(), result(), select(), etc.

[Error - 12:08:04] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'funs' of null
  Code: -32603 

I tried to find the problem and i saw that the extension works with mysql driver, but i am not sure if this causes the problem,

Can you fix it? that would be great! i really like this extension

Sorry for my english.

**Comment by smallp** [comment]
Can you print the whole sentence? Try the simplest sentence, such as `$this->db->where()->get()->row()`. Figure out if the extension works.
