### ISSUE TITLE
I'm loading models differently

### ISSUE THREAD

**Issue by farzher** [smallp/vscode-ci#13]
instead of

```
$this->load->model('user_model');
$this->user_model->login();
```

I do

```
m('user')->login();
```

(it autoloads if necessary)

Could you add a config option to let me set my own model regex?

**Comment by smallp** [comment]
Sorry, I can't. The whole regex is based on `$this`. If it found the sentence begins with `$this`, it would work, otherwise it will pass. It's too difficult for me to change the logic.
