### ISSUE TITLE
Autoloaded models with alias

### ISSUE THREAD

**Issue by skmd87** [smallp/vscode-ci#14]
Thank you for this great work.
Im facing a problem where my models are loaded through config/autoload.php with alias ex:
`$autoload['model'] = array('Flash_model'=>'flash','Rules_model'=>'rules');`

I tried to change the settings to
`"CI.model": [{"Flash_model":"flash"}],`

but still not working? is aliasing supported?if no, any plans to support it?

**Comment by smallp** [comment]
Got it.

**Comment by BagiraHun** [comment]
There's also problem with third party packages, defined the following (also autoload) way:
`$autoload['packages'] = array(APPPATH.'third_party/fpdf/', APPPATH.'third_party/fpdi/');`
The parser try to load from `application\libraries\Fpdf.php`, and got error:
`{ errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '[censored]...\\application\\libraries\\Fpdf.php' }`
The lib is at `application\third_party\fpdf\libraries\Fpdf.php`

**Comment by skmd87** [comment]
Thanks for the quick update.
I have changed the settings to the following:
` "CI.model": {
    "Flash_model": "flash"
  },
`
But im getting the following error: 
Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'consts' of null
Am I doing something wrong?

**Comment by smallp** [comment]
try { "flash": "Flash_model" }

**Comment by skmd87** [comment]
I tried that also and im getting this error :
`Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'name' of null`

**Comment by smallp** [comment]
em... I cannot repeat this error. It works fine in my workspace. Can you use `$this->flash_model->` to trigger the Completion? Is the `flash_model` in a sub-folder?

**Comment by smallp** [comment]
I have checked and modified the code may cause this issue. You can try again and find out if it still  exists.

**Comment by jagad89** [comment]
I got same error, `Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'name' of null`, another question is, how to load multiple models alias ? I tried  2 ways
```
"CI.model":[ 
        {"company_goal":"Company_goal_model"},
        {"company":"Company_model"},
        {"company_password_reset":"Company_password_reset_model"}
     ] 
```
and
```
"CI.model":[ 
        {
            "company_goal":"Company_goal_model",
            "company":"Company_model",
            "company_password_reset":"Company_password_reset_model"
        }
     ] 
```
it both cases it shows below error
`Notification handler 'workspace/didChangeConfiguration' failed with message: path.split is not a function`

**Comment by smallp** [comment]
@jagad89 it is `"CI.model":{
            "company_goal":"Company_goal_model",
            "company":"Company_model",
            "company_password_reset":"Company_password_reset_model"
        }`
Array means loading without alias, and object means alias.

**Comment by jagad89** [comment]
I got below message in output window
`[Error - 7:48:28 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'consts' of null`

My VS Code info as below

> Visual Studio Code
> Version 1.21.1
> Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
> Date 2018-03-14T14:46:47.128Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64
>

**Comment by jagad89** [comment]
I studied the code I don't know TypeScript but guess the error occur due to exception generated in [this](https://github.com/smallp/vscode-ci/blob/master/server/src/parse.ts) file on line number 34 in file. How to find the exception cause ?

**Comment by smallp** [comment]
I know it, but I don't know how to repeat this error. I'll fix it in next version.

**Comment by hjanos1** [comment]
I have a solution to the error you mentioned:
[Error - 12:28:34 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'consts' of null

The error occurs because it wants to parse a file which does not exist.

For me, it was caused by the autoload feature. Here is my relevant config:
"CI.library": ["database", "GeoIP2", "session"],

Since "database" is not a real library, it is just a way of telling CI to automatically connect to the database, the file does not exist, therefore the error occurs.

**Comment by smallp** [comment]
Got it. I know how to fix it.
