### ISSUE TITLE
Annoying console errors

### ISSUE THREAD

**Issue by manuman94** [smallp/vscode-ci#15]
Since yesterday's VSCode update, I'm getting this error in the console when I press ')' and ',' keys:
`[Error - 09:51:55] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property '0' of undefined
  Code: -32603 `

What is making VSCode fail?

Thanks for providing such a great extension (it has been part of my must-be-installed).

Greetings.

**Comment by jenishj-crest** [comment]
Have facing same issue.

**Comment by sys4soft** [comment]
Issues here also:
`start small-ci on 11032
[Error - 19:51:14] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property '0' of undefined
  Code: -32603 `

This messages are always displaying in the console.

**Comment by smallp** [comment]
Yeh, I knew it. Fix it soon.

**Comment by manuman94** [comment]
Thanks a lot! 

Greetings.
