### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by takakeiji** [smallp/vscode-ci#2]
This plugin works pretty good, but I have two complaints I think can be improved.
- Every time I use autocomplete tor any instruction adds a new line (it’s very frustrating).
- Every time I use autocomplete adds “this” selected but no “$this”, behabior could be configurable!

That's all and thank you for your work

**Comment by smallp** [comment]
I have tried in Ubuntu and Windows, and it works well.
You can try again without this extension. If you still use autocomplete tor any instruction adds a new line, you should add a issue for VSCode. I just follow its tuition.
As for the 'this', I believe it is better to add it to your user snippet. It is a better solution.
