### ISSUE TITLE
It doesn't work in version 1.24.1 of VS Code

### ISSUE THREAD

**Issue by sancdan** [smallp/vscode-ci#21]
I tried to remove and install again, but it doesn't work. Do you have any idea? I used it before and there wasn't any problem with previous versions.

**Comment by michaeljdiaz** [comment]
Yes, I have the same issue. I just tested on VS 1.24.1 and isn't working.

**Comment by smallp** [comment]
I have always used the latest version of VSCode, and it work fine. Now I'm in 1.25.0, is anyone else has the same issue?
