### ISSUE TITLE
CPU overload

### ISSUE THREAD

**Issue by sanarena** [smallp/vscode-ci#22]
This extension is causing 100% cpu usage after few hours of working with codeigniter projects.
Once this issue happen, CPU load goes to 100% for "Code Helper" process and vscode start work in a weird way (no more autocomplete show up for any function, other plugins does not work properly) and it is necessary to quit and reopen visual studio code.
Additionally, upon exit, Code Helper continue to run and need to be killed manually.
<img width="672" alt="2018-07-04_17-36-48" src="https://user-images.githubusercontent.com/1212959/42269492-dbbc71b8-7fb0-11e8-98e7-2e53568f2435.png">
<img width="1168" alt="2018-07-04_17-37-21" src="https://user-images.githubusercontent.com/1212959/42269512-eae84f54-7fb0-11e8-9182-25a80503fb3c.png">
I have to disable this extension until issue is fixed as I require laptop battery to be preserved during the day.

**Comment by smallp** [comment]
Em... That's weird. This extension is called when you open a file or tap something. If you do nothing, it won't use any CPU. So have you install any other extensions? Is VScode works fine after you disable this extension?

**Comment by sanarena** [comment]
I've disabled it, and problem with this one gone away, however problem with php intellisense appeared which caused php 7 process to go 100%. I assume something is horribly wrong with my vscode setup. Using Atom until I can find a fix for that.

**Comment by smallp** [comment]
What a pity. As the new version of VS code has been released, you can try again. Maybe this issue have been fixed.
