### ISSUE TITLE
[Request] Custom system folder name and location

### ISSUE THREAD

**Issue by SHTO88** [smallp/vscode-ci#25]
We are not using standard codeigniter. Our folder structure looks like this:

- app
- core
- core/CI

Here application folder has been renamed to app and system folder is renamed to CI and placed under core folder.

Is it possible to support such structures?

**Comment by smallp** [comment]
![2018-12-17 23-43-54](https://user-images.githubusercontent.com/10028968/50097825-a7ab2e00-0255-11e9-9e28-cdda206a9530.png)
here you are.
You can set CI.app to app and CI.System to core/CI

**Comment by SHTO88** [comment]
I updated user settings and workspace settings. But it seems this is still referring to system folder:
![image](https://user-images.githubusercontent.com/17476161/50120462-99700880-027b-11e9-894d-831d8dd4f6ad.png)

**Comment by smallp** [comment]
I know that, but it still work fine. You can set CI.other=[] to avoid this error.
