### ISSUE TITLE
Filename case after click on class member

### ISSUE THREAD

**Issue by Nakiloe** [smallp/vscode-ci#26]
When I click on a class member (from controller to model, in PHP), the file is opened, on the correct member, but the filename is shown with first letter in uppercase, while the real file is lowercase (see attached screenshot). I'm on MacOS, so if I make changes and save them, it creates a second file instead of overwriting my file.

VS Code version: Code 1.30.2
![vscode_filename](https://user-images.githubusercontent.com/45621005/51603466-2c9afe80-1f0a-11e9-888d-286b777f5ae7.png)

**Comment by smallp** [comment]
Linux and Unix is case sensitive. Now my extension can only parse the capitalized filename, so if your file is lowercase, the extension would stop work. However, I tried this case in Linux and I cannot open the model. Is this different between Linux and Mac?

**Comment by Nakiloe** [comment]
Mac is also case sensitive (hence the file duplication). As said, the model is opened, but with the capitalized filename :/

**Comment by smallp** [comment]
I don't have a Mac yet :( I'll find a Mac to reproduce this issue and then I can fix it.

**Comment by smallp** [comment]
It seems you have  modified the framework. In the source of CI's Loader, the file name of model must capitalize the initial letter. So I just open the file with capitalized words. 
There is no better solution yet. :(

**Comment by dylanwinn** [comment]
@smallp I don't think that's correct. CI expects the *class* name to be capitalized, but the *file* name to be all lower case.

```
		$model = strtolower($model);

		foreach ($this->_ci_model_paths as $mod_path)
		{
			if ( ! file_exists($mod_path.'models/'.$path.$model.'.php'))
			{
				continue;
			}

			if ($db_conn !== FALSE AND ! class_exists('CI_DB'))
			{
				if ($db_conn === TRUE)
				{
					$db_conn = '';
				}

				$CI->load->database($db_conn, FALSE, TRUE);
			}

			if ( ! class_exists('CI_Model'))
			{
				load_class('Model', 'core');
			}

			require_once($mod_path.'models/'.$path.$model.'.php');

			$model = ucfirst($model);

			$CI->$name = new $model()
```

**Comment by smallp** [comment]
@dylanwinn You can check out the version of CI. This extension is based on CI 3.X.
