### ISSUE TITLE
Add the possibility to disable the detection and/or display of symbols in order to use this extension in addition to intellisence.

### ISSUE THREAD

**Issue by NicolasGrimonpont** [smallp/vscode-ci#27]
Currently it is not possible to disable the display of symbols that are all duplicated.

<img width="1439" alt="capture d ecran 2019-02-10 a 03 28 10" src="https://user-images.githubusercontent.com/32468475/52530442-96761f00-2ce4-11e9-9dc8-b3afcd35a382.png">

**Comment by smallp** [comment]
Finished in next version.
