### ISSUE TITLE
the extension do not work

### ISSUE THREAD

**Issue by changchun456** [smallp/vscode-ci#28]
i installed the extension,but it not worked,when i insert $this-> 
![image](https://user-images.githubusercontent.com/5118863/54655219-0f467300-4afc-11e9-9584-6b29ed4dc4f9.png) this list display,is not CI

**Comment by smallp** [comment]
Can you show the struct of you folder?

**Comment by boskiv** [comment]
I have the same issue
* download new CI 
* open it in VSCode
![Screenshot 2019-04-18 at 10 39 49 PM](https://user-images.githubusercontent.com/1939783/56386653-0cd65680-622b-11e9-91cd-84be6fd801fb.png)

**Comment by smallp** [comment]
> I have the same issue
> 
>     * download new CI
> 
>     * open it in VSCode
>       ![Screenshot 2019-04-18 at 10 39 49 PM](https://user-images.githubusercontent.com/1939783/56386653-0cd65680-622b-11e9-91cd-84be6fd801fb.png)

It does not support output. Try input or db. BTW, now you can run `CI: refresh Model` command to figure out if this extension starts.

**Comment by namleasia** [comment]
How to run CI: refresh Model
Please help!

**Comment by boskiv** [comment]
@namleasia I think ctrl+shift+p pane, you looking for

**Comment by smallp** [comment]
> How to run CI: refresh Model
> Please help!

F1 and press CI. ctrl+shift+p also works.

**Comment by namleasia** [comment]
Thank you so much @boskiv and @smallp 
It works for me. (CI 3.1.9)
