### ISSUE TITLE
To make model alias lowercase is unnecessary...

### ISSUE THREAD

**Issue by golee** [smallp/vscode-ci#3]
Hello.

I use this extension usefully(Thank you), but there is one thing I do not understand.

I prefer camelCase style ClassName 
so the codes are like
$this->load->model('mymodel', 'myModel');

then,
$this->myModel->(Intellisense not work);

Is there any reason to keep policy to lowercase model alias ?

My suggestion  is...
line 310 of server/control.ts
alias = a[1].trim().slice(1, -1).toLowerCase();
->
alias = a[1].trim().slice(1, -1);

**Comment by smallp** [comment]
Got it. I'll fix it soon.
