### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by danfiza** [smallp/vscode-ci#31]
Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'funs' of null
  Code: -32603 

Getting the above error when hovering over functions like $this->db->query

**Comment by smallp** [comment]
Can you show me the whole line? The parser is based on grep, so it may die in some complex situation.

**Comment by danfiza** [comment]
> Can you show me the whole line? The parser is based on grep, so it may die in some complex situation.

The following throws the above exception 

$this->db->query($sql)->result_array();

**Comment by smallp** [comment]
It's the simplest case. I have tried this case and this extension works fine. Does it work fine with `$this->input`? Have you change the name of `system`?

**Comment by danfiza** [comment]
$this->input works fine, and no the system folder name has not been changed

**Comment by smallp** [comment]
OK, now just leave it. I'll add more debug info in next version to know what happened.

**Comment by danfiza** [comment]
Thanks when I get some time I'll try to debug myself if I can
