### ISSUE TITLE
found a BUG vscode-ci

### ISSUE THREAD

**Issue by itsmemanoj** [smallp/vscode-ci#33]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->option_v
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->option_va
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->option_val
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->option_valu
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
Hello! You have found a BUG! It would be very helpful if you can add a issue in github!
Add issue here: https://github.com/smallp/vscode-ci/issues/new
Here is the main content. You can just keep the main content when you submit.
$this->data[$value->options] = $value->option_value
[["Pagination",{"funs":{},"classData":{"name":"CI_Pagination","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/system/libraries/Pagination.php","range":{"start":{"line":48,"character":3},"end":{"line":48,"character":24}}}},"variable":{}}],["Common",{"funs":{},"classData":{"name":"Common","location":{"uri":"file:///d%3A/xamp7/htdocs/myproject/application/libraries/Common.php","range":{"start":{"line":5,"character":4},"end":{"line":5,"character":19}}}},"variable":{}}]]
[Error - 4:59:24 PM] Server initialization failed.
Error: command 'extension.refreshModel' already exists
	at v.registerCommand (c:\Users\mycomputer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:532)
	at Object.registerCommand (c:\Users\mycomputer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:699)
	at ExecuteCommandFeature.register (c:\Users\mycomputer\.vscode\extensions\small.php-ci-0.3.2\node_modules\vscode-languageclient\lib\client.js:1501:53)
	at ExecuteCommandFeature.initialize (c:\Users\mycomputer\.vscode\extensions\small.php-ci-0.3.2\node_modules\vscode-languageclient\lib\client.js:1491:14)
	at LanguageClient.initializeFeatures (c:\Users\mycomputer\.vscode\extensions\small.php-ci-0.3.2\node_modules\vscode-languageclient\lib\client.js:2168:21)
	at connection.initialize.then (c:\Users\mycomputer\.vscode\extensions\small.php-ci-0.3.2\node_modules\vscode-languageclient\lib\client.js:1888:18)

**Comment by smallp** [comment]
Good shot! I'll fix it soon.
