### ISSUE TITLE
[Bug] Loading model in subfolder without '/'

### ISSUE THREAD

**Issue by HardysJin** [smallp/vscode-ci#34]
File Structure:
**application
|-- models
|---- sub_folder
|------  my_model.php**

Loading my_model by: `$this->load->model("sub_folder/my_model")`.

But `$this->my_model` will not be recognized.

Can u please add that functionality? Thanks!

Edit:
Emm...
`$this->load->model("/sub_folder/my_model")` actually works
This should be a bug then. 
Path for opened file is: **application/models//sub_folder/my_model.php** which is not correct

**Comment by smallp** [comment]
Got it.

**Comment by HardysJin** [comment]
Hi,
Another case issue I have noticed: `$this->load->model("sub_folder/My_model")`
`$this->my_model` is defined but not `$this->My_model`
Using `$this->my_model->func()` will cause `Fatal error: Call to a member function func() on a non-object`. 
Since I work on a large legacy codebase, it will be very appreciated if you can help fix this issue. Ignore me if it is too complicate to implement. Thanks!

**Comment by smallp** [comment]
You can wait for next version.

**Comment by smallp** [comment]
> File Structure:
> **application |-- models |---- sub_folder |------ my_model.php**
> 
> Loading my_model by: `$this->load->model("sub_folder/my_model")`.
> 
> But `$this->my_model` will not be recognized.
> 
> Can u please add that functionality? Thanks!
> 
> Edit:
> Emm...
> `$this->load->model("/sub_folder/my_model")` actually works
> This should be a bug then.
> Path for opened file is: **application/models//sub_folder/my_model.php** which is not correct

I have tried that, but it works.
In my case, File Structure:
**application |-- models |---- test |------ Hello.php**
```
$this->load->model('test/Hello');
$this->hello->isAdmin();
```
Completion and Definition works fine. So can you give more infomation? BTW, the case issue will be fixed soon.

**Comment by HardysJin** [comment]
Yea, Completion and Definition works fine. But when you actually load that page on browser, it will give you `Fatal error: Call to a member function isAdmin() on a non-object` because models loaded in CI is case sensitive.
