### ISSUE TITLE
Unable to loading model without subfolder

### ISSUE THREAD

**Issue by ho88** [smallp/vscode-ci#35]
I installed the last version: 0.3.5, but see these images

![1](https://user-images.githubusercontent.com/59162224/71345587-06973780-257b-11ea-934b-ff25743e7dcf.PNG)

When saving php file or running (Syntax Error):

![2](https://user-images.githubusercontent.com/59162224/71345624-23cc0600-257b-11ea-880c-9e843fea7fdd.PNG)

with removing subfolder when saving php file or running (Also Hover and hint don't work in this state) : 

![3](https://user-images.githubusercontent.com/59162224/71345715-5b3ab280-257b-11ea-8279-052aae530725.PNG)

I think version 0.3.3 works fine for this issue. neither this problem nor case problem!
So I downgraded to 0.3.3 until fixing both problems.

**Comment by smallp** [comment]
Got it.
