### ISSUE TITLE
Spaces between (->) will let "Go To Definition" not work

### ISSUE THREAD

**Issue by Fightsea** [smallp/vscode-ci#36]
I have CI code like this: 

$this->load->model("m_groups");
$group_owner = $this->m_groups->read_owner($groups_id);

However, due to team work coding style, I have to add spaces between '->', like this:
$group_owner = $this -> m_groups -> read_owner($groups_id);

After add spaces between '->', the "Go To Definition" will not work as well.
Hope it can be fixed.
Thanks!

**Comment by smallp** [comment]
Em... Strange coding style. OK, I'll fix it soon.

**Comment by Fightsea** [comment]
Thanks a lot. That's pretty much helpful!
