### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dzulqornain04** [smallp/vscode-ci#38]
- Issue Type: `Performance`
- Extension Name: `php-ci`
- Extension Version: `0.3.6`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\MDQ04.000\small.php-ci-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smallp** [comment]
You have not upload your file. I'll deal with it after you uploaded.
