### ISSUE TITLE
Goto Definition saying "No definition found for XX"

### ISSUE THREAD

**Issue by jerrmhs** [smallp/vscode-ci#4]
The autocomplete is working perfectly but when it does autocomplete I can not use Goto definition or the Peek functionality of VS Code.

I am loading the workplace from a windows file systems and on windows 7 and have the controller/model in the respected places in the application folder.

I have the code attached, I tried with and with aliasing the models name, both will autocomplete but neither will use goto functionality.
![goto](https://user-images.githubusercontent.com/10408027/28684163-3dd54296-72b8-11e7-8bbf-ac036bbbd271.PNG)
![autocom](https://user-images.githubusercontent.com/10408027/28684164-40456eac-72b8-11e7-9d6e-01b77c4cd5a8.PNG)

**Comment by smallp** [comment]
Got it. I'll fix it soon.

**Comment by smallp** [comment]
Sorry, but I cannot repeat this bug.
![default](https://user-images.githubusercontent.com/10028968/28713003-f02f0276-73bf-11e7-9f6e-7b4a08e0945a.png)
It works fine for me. Can you show your filename of this model?

**Comment by jerrmhs** [comment]
So I did some testing and I found out it does not work if the work space is opened in a file server (\\PHPDEV\www) but if i move the files to a local folder on my desktop the extensions works just fine. Could this be a bug within the extensions or a bug on the file server/windows?

**Comment by smallp** [comment]
I have not tested so much in windows. So what's the situation? You open the folder in ftp server? Or file not in your local disk?

**Comment by jerrmhs** [comment]
The folder is on a share drive on the network. You can open it just like any other folder using Windows File Explorer. VS Code opens the folder as a work station and i can still open and see all the file, sometimes it takes a bit for a change to sync though but other then that it works the same. Example (\\phpdev\www)

**Comment by smallp** [comment]
I see. Maybe I know the reason. The way extension read the file is finding the file with `file://c/test.php`, however, as your file is not in local folder, it fails to read the file. So can you give me your email? I'll try to fix it and then send you the extension to test it as I don't has the similar situation.

**Comment by jerrmhs** [comment]
Here it is. jerrmhs@gmail.com

**Comment by smallp** [comment]
Have you receive my email? If so, please give me the output to location the error

**Comment by jerrmhs** [comment]
Found it in Junk. Looking now.

**Comment by jerrmhs** [comment]
So if I load the copied folder on my desktop i see a string of commands, in the PHP Language Server I get a long list of Parsing file: //XX along with "[Info  - 11:31:13 AM] 0 Packages
[Info  - 11:31:13 AM] All 438 PHP files parsed in 36 seconds. 104 MiB allocated."
And in small-ci I get a list of libraries and models i have loaded.

But if I load my server folder from \\phpdev\www I get "[Info  - 11:29:48 AM] 0 files total
[Info  - 11:29:48 AM] Indexing project for definitions and static references
[Info  - 11:29:48 AM] Indexing project for dynamic references
[Info  - 11:29:48 AM] 0 Packages
[Info  - 11:29:48 AM] All 0 PHP files parsed in 0 seconds. 96 MiB allocated."
in PHP Language Server and for some reason the small-ci panel took over 5 minutes to load up, once that was loaded it showed the same list as the local copy and the function hinting started working again, but still now definitions. I assume that error is because in the "Php Language Server" panel said 0 files total.

Let me know if there is anything more you want me to test or any settings you want changed.

**Comment by jerrmhs** [comment]
Figured out a solution. If you map the network drive (windows:  then open it in vs code it will take a while but after about 5 min it will parse though all the files and then small-ci will start doing its thing. 
![solmap](https://user-images.githubusercontent.com/10408027/29385693-83523e70-828d-11e7-9fb0-3ec4218c0222.PNG)
![solcode](https://user-images.githubusercontent.com/10408027/29385698-85c45e0e-828d-11e7-8815-ab51dac58955.PNG)

**Comment by smallp** [comment]
I need something like that. 
![2017-08-17 10-17-22](https://user-images.githubusercontent.com/10028968/29393297-8fcc615a-8335-11e7-965c-2601f4c1b566.png)

The first line is the root path of your folder, such as `/W:/bar/`. The rest of the lines is the file that the extension has read. If you open a file that has `$this->load->model()`, the file path of the model will display here.
If the paths are right, the problem is the way open the files or read the files. Otherwise, I need to send the extension again.
BTW, Is it work fine in autocomplete? The problem is only unable to go to definition?

**Comment by jerrmhs** [comment]
The output displays the correct information, and the autocomplete works just fine, its the definition part that does not work. But I think that was because it was not parsing the files. When I mapped the drive it started parsing them and working as expected.
![small-ci](https://user-images.githubusercontent.com/10408027/29420678-7e2d0836-8327-11e7-969b-523dd608eb91.PNG)

**Comment by smallp** [comment]
Please checkout your email. I think we can solve it with this shoot.

**Comment by jerrmhs** [comment]
The file names are correct. and I can ctrl+click and they open just fine. I believe the program has to do when i first open the workplace folder and in PHP Language Server panel i see this 
"[Info  - 12:12:16 PM] 0 files total
[Info  - 12:12:16 PM] Indexing project for definitions and static references
[Info  - 12:12:16 PM] Indexing project for dynamic references
[Info  - 12:12:16 PM] 0 Packages
[Info  - 12:12:16 PM] All 0 PHP files parsed in 0 seconds. 96 MiB allocated."

This panel is different when i open the workplace in a mapped drive or if i open locally. It instead shows this 
"...
Parsing file:///w:/application/controllers/CdrFtp.php
Parsing file:///w:/application/controllers/Login.php
Parsing file:///w:/application/controllers/RssFeeds.php
Parsing file:///w:/application/controllers/E911.php
Parsing file:///w:/application/controllers/QuickBooks.php
Parsing file:///w:/application/controllers/Home.php
Parsing file:///w:/application/third_party/NutshellApi.php
Parsing file:///w:/application/third_party/test.php
[Info  - 11:57:46 AM] 0 Packages
[Info  - 11:57:46 AM] All 439 PHP files parsed in 176 seconds. 104 MiB allocated."

I bet for some reason when the folder is opened it does not wait for the filer server to get the full list of folders so it just says 0 files.

**Comment by smallp** [comment]
Em, I want to know the output in small-ci panel, nor PHP Language Server panel. PHP Language Server is the built-in extension for php. In small-ci panel, it will display the full path of the file you opened, and the response of the extension when you try to go to definition. It they are different in the first part, I'll fix it soon. Otherwise... I don't know why.

**Comment by jerrmhs** [comment]
The output names where correct.
file:///w%3A/application/controllers/Hospitality.php
file:///w%3A/application/controllers/Hospitality.php

file:///w%3A/application/controllers/Hospitality.php
{ uri: 'file:///w%3A//system/database/DB_query_builder.php',
  range: 
   { start: { line: 1412, character: 17 },
     end: { line: 1412, character: 83 } } }
file:///w%3A/application/models/HospitalityDB.php
{ uri: 'file:///w%3A//application/models/HospitalityDB.php',
  range: 
   { start: { line: 196, character: 17 },
     end: { line: 196, character: 31 } } }

**Comment by smallp** [comment]
Yes, that's is. The correct uri is file:///w%3A/application/models/HospitalityDB.php however the returned uri is file:///w%3A//application/models/HospitalityDB.php, so it fails. I'll check my code to find out why it happens.
