### ISSUE TITLE
Error trying to read Common.php

### ISSUE THREAD

**Issue by leonglz** [smallp/vscode-ci#40]
When I start VS Code I get this error in output panel:

> [Error - 9:17:56] Notification handler 'workspace/didChangeConfiguration' failed with message: ENOENT: no such file or directory, open '/.../system/core/Common.php'

I changed system folder to 'ci_sistema' in both User and Workspace settings and apparently it is still trying to read 'system'.

Also, if I run refresh Model command, I get:

> read dir fail:/.../ci_app/models/

There's this message at the bottom of editor:

> small-CI initing...

**Comment by shipan3452** [comment]
i have same problem too

**Comment by ardiansyah25** [comment]
i have some problem too

**Comment by smallp** [comment]
Get. I'll try it in windows. You can rollback to pre version to use.
