### ISSUE TITLE
Error while enable this extension

### ISSUE THREAD

**Issue by Fightsea** [smallp/vscode-ci#41]
OS: Windows 8.1
VSCode: v1.42.1
Source Code folder is located on "C:\\_data\\_code\\git\\BDM_API"

Since the latest update (0.3.7), I always got error while enable this extension.
And the extension does not functionally work fine.
Error message is listed below:

--------------------
Debugger listening on ws://127.0.0.1:6011/5bede1f9-2f80-4f46-8e6d-4cb0d41a4347
For help, see: https://nodejs.org/en/docs/inspector
start small-ci on 5668
[Error - 下午4:14:27] Notification handler 'workspace/didChangeConfiguration' failed with message: ENOENT: no such file or directory, open '/c%3A/_data/_code/git/BDM_API/system/core/Common.php'

**Comment by ardiansyah25** [comment]
i have same problem too

**Comment by smallp** [comment]
Get. I'll try it in windows. You can rollback to pre version.

**Comment by Fightsea** [comment]
Ii works fine now with new release version 0.3.9, thanks very much!
