### ISSUE TITLE
Still can't find Common.php

### ISSUE THREAD

**Issue by leonglz** [smallp/vscode-ci#42]
With the last change you made command _refresh Model_ now works, but it still says it can't find file _core/Common.php_ and it is stuck in _small-CI initing..._.

I think the problem is it is not using the custom name for the _system_ folder. Mine is _ci_sistema_, which is set in the extension settings, but the message in the Output panel says:

>[Error - 18:44:20] Notification handler 'workspace/didChangeConfiguration' failed with message: ENOENT: no such file or directory, open 'c:\...\projectFolder/**system**/core/Common.php'

**Comment by smallp** [comment]
I see. You should change the seting of  `CI.other` to `[]`. I'll fix that in next version.
