### ISSUE TITLE
Go to definition for "view" files

### ISSUE THREAD

**Issue by aswinkumar863** [smallp/vscode-ci#46]
It would be more productive if go to definition feature for view files available. For example, `Ctrl + click` of `index/home` in 

```
$this->load->view('index/home', $vars);
```
should open the `application/views/index/home.*` file. Here `*` is the extension, php or whatever.

**Comment by smallp** [comment]
Got it.

**Comment by aswinkumar863** [comment]
FYI, I have implemented a similar [feature ](https://github.com/aswinkumar863/smarty-vscode-support/blob/master/client/src/language/documentLink.ts#L14) in my vscode [extension](https://marketplace.visualstudio.com/items?itemName=aswinkumar863.smarty-template-support). Hope that is helpful for you.

**Comment by smallp** [comment]
I know how to do this feature, but I'm too busy to do that. Now I have changed my job to be a java engineer. I'm busy to learn java. If you are able to add this feature, you can pull a request, or I'll do that in Jan, 2021, maybe.

**Comment by aswinkumar863** [comment]
@smallp I understand your situation. And I am happy to do a pull request but I m struggling to get  `view` method parameters using the [parser](https://github.com/smallp/vscode-ci/blob/master/server/src/parse.ts). Any help would be highly appreciated.

**Comment by smallp** [comment]
There is a easy way to do that. Add a new function in `parse.ts`. Add `view` in `parse.re` to find out `->view("(.*?)"`. Then, you can match all the matched patten to find out if there is a view file. If so, add the info into DocumentLink list and return.
Don't forget to add a configuration to set the file type of view files.
