### ISSUE TITLE
This extension not work in defined $application_folder 

### ISSUE THREAD

**Issue by tiansin** [smallp/vscode-ci#5]
index.php defined $application_folder, this extension not work!

like:
$application_folder = 'application/home';

**Comment by smallp** [comment]
em.... Yes, it works only if the application_folder and the system_folder are in the same folder. It seems you have muti-application, however, it is so hard to handle muti-application as this extension is designed for single application.

I'll consider that add a setting to solve this problem. You can set the setting to develop in a single application
