### ISSUE TITLE
Error on CI 4.0.4 - reading models

### ISSUE THREAD

**Issue by sorinsfirlogea** [smallp/vscode-ci#53]
It seems that there is something wrong with the path where the extension is trying to read data. Looks like is confusing it with CI3 structure (application/models). It only happens when hovering over some methods like getResultArray or getRowArray
Example: 
`return $this->db->query($sql)->getResultArray();`

This is the output of the error:
```
start small-ci on 20452
read dir fail:/home/sorin/Development/erp/application/models/
[Error - 9:40:46 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'funs' of null
  Code: -32603 
```

**Comment by smallp** [comment]
It does not support CI4. It's designed for CI3.
CI4 is based on namespace. Maybe `PHP IntelliSense` is enough for you.
