### ISSUE TITLE
No params hint on CTRL+SHIFT+SPACE for models loaded from a subfolder without leading "slash"

### ISSUE THREAD

**Issue by anvltu** [smallp/vscode-ci#54]
When I load a model from a subfolder without using leading slash ("/") ( $this->load->model('subfolder/model') ) I won't get a parameters hint by pressing CTRL+SHIFT+SPACE. It starts working with the model functions after adding a leading "/" in the model path ( $this->load->model('/subfolder/model') ).

**Comment by smallp** [comment]
Got it.

**Comment by smallp** [comment]
I may misunderstand. What is the supposed action? 
> I won't get a parameters hint by pressing CTRL+SHIFT+SPACE.
Can you give a full case? Is you said, it should give a hint, like `odel` after you typing `subfolder/m`?

**Comment by anvltu** [comment]
I often place caret after the model function opening bracket and press CTRL+SHIFT+SPACE in order to get a hint about function parameters. I don't get this hint if no leading slash in model load function.

**Comment by anvltu** [comment]
Here's what I mean: https://i.stack.imgur.com/I8V0X.png

**Comment by anvltu** [comment]
Here's my example
![Снимок экрана в 2021-01-18 16-31-52](https://user-images.githubusercontent.com/75672916/104910435-20d45c80-59ab-11eb-99d2-93fa94a0d2b4.png)

**Comment by anvltu** [comment]
Also, CTRL + left mouse click not working on a model functions for models which have been loaded without leading slash.
