### ISSUE TITLE
goto definition

### ISSUE THREAD

**Issue by Collanteslu** [smallp/vscode-ci#56]
If I trie to go definition to a model that is on a folder into model folder don't do nothing.

**Comment by smallp** [comment]
Is the autocompletion work well? Such as `$this->model->`, it should show all functions of the model.

**Comment by Collanteslu** [comment]
No it doest apear. i use to call de modelsde autoload in config in
codeigniter.


Luis Collantes Villalba
*Desarrollador*
*660752174* · collanteslu@gmail.com

   [image: twitter] <http://twitter.com/collanteslu> [image: linkedIn]
<http://es.linkedin.com/pub/luis-collantes-villalba/61/a7b/5b4/>  [image:
YouTube] <http://www.youtube.com/channel/UC475vFiRKfhJ1acvNlxiYWg> [image:
Google+] <http://plus.google.com/u/0/+luiscollantes/about/p/pub>

**Comment by smallp** [comment]
So that's because this extension have not load your models. Have you write `$this->load->model('folder/model')`? Can you show a piece of your code?

**Comment by Collanteslu** [comment]
![Captura de pantalla 2021-02-10 a las 12 31 46](https://user-images.githubusercontent.com/3098691/107505274-bd4de100-6b9c-11eb-9953-c6ad8536a2a6.png)

**Comment by Collanteslu** [comment]
![Captura de pantalla 2021-02-10 a las 12 55 16](https://user-images.githubusercontent.com/3098691/107507139-6b5a8a80-6b9f-11eb-9987-40d0857a3da7.png)

**Comment by Collanteslu** [comment]
![Captura de pantalla 2021-02-10 a las 13 04 23](https://user-images.githubusercontent.com/3098691/107507916-8c6fab00-6ba0-11eb-8a2d-a740ebb41174.png)
It happend something strange if i change de name folder it begin to works , but when i reload the project doesnt work.

**Comment by smallp** [comment]
That's strange. I clone your project and this extension works fine for me.
<img width="1440" alt="WX20210213-153337@2x" src="https://user-images.githubusercontent.com/10028968/107844712-e1195d00-6e10-11eb-9db7-21bcd87291aa.png">
