### ISSUE TITLE
Custom `system` folder location

### ISSUE THREAD

**Issue by fabiospampinato** [smallp/vscode-ci#6]
My project structure looks like this:

```bash
.
├─┬ app
│ ├── application
│ ├── system
| └── models
├── config
└── resources
```

The Codeigniter root is `app`, therefor this extension cannot find the `system` folder. There should be a setting for setting CI's root or the path to the `system` folder.

**Comment by smallp** [comment]
Got it. But I'm busy recently, so you'll wait for a while.

**Comment by fabiospampinato** [comment]
Ok, thanks for your time.

**Comment by fabiospampinato** [comment]
That's great, but I'm getting a `The small-ci server crashed 5 times in the last 3 minutes. The server will not be restarted.` error as soon as I open a controller's file.

I'm using Code v1.18.0.

**Comment by smallp** [comment]
Now it works fine.
