### ISSUE TITLE
I want PHPDocumentation information to be displayed.

### ISSUE THREAD

**Issue by pabian84** [smallp/vscode-ci#60]
Thanks for developing a good plug-in.

When a function inside the model is mouse-overed, only part of the phpdocumentation is displayed(ex. $this->My_Model->My_Function($param)).
It would be much more helpful if the phpdocumentation information also shows the value of @param and @return.

Current 
![K-20210721-357589](https://user-images.githubusercontent.com/31716595/126413757-382e8dcf-9b5a-489e-8400-e910e7762991.png)

Want
![K-20210721-357902](https://user-images.githubusercontent.com/31716595/126413844-03a5e014-b007-4a9f-980b-045307ab3ea0.png)

**Comment by smallp** [comment]
I have saved the info of params. You can get the info when you fill the params, but this info has not been shown in the documentation. You can add it in documentation, and later I can publish it. As now I'll not maintain this extension.
