### ISSUE TITLE
vscode browser

### ISSUE THREAD

**Issue by abunaum** [smallp/vscode-ci#61]
i can't install extension in vscode browser (vscode.dev)

**Comment by smallp** [comment]
Any error info? I install this extension in 1.61.2 and it works fine.

**Comment by abunaum** [comment]
That say "the extension is not avaliable in visual studio code for the Web browser" ( https://imgshare.io/images/2021/11/01/Screenshot_20211102_093130.jpg)

**Comment by smallp** [comment]
I see. You are using vscode in web browser. Let me check the document first.

**Comment by smallp** [comment]
It will take a long time to update this extension to Web extension. Maybe I'll do that in some day. You are welcome to contribute this.
