### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by f4r424hm3d** [smallp/vscode-ci#62]
- Issue Type: `Performance`
- Extension Name: `php-ci`
- Extension Version: `0.4.2`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\faraz\AppData\Local\Temp\small.php-ci-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smallp** [comment]
When would it causes high cpu load? For a while or for a long time?
