### ISSUE TITLE
Visual Code output window from small-ci 

### ISSUE THREAD

**Issue by Aldo-f** [smallp/vscode-ci#64]
https://stackoverflow.com/a/61936077/4249483

**Comment by smallp** [comment]
It was asked years ago. Please show me the file sample and then I can handle it.

**Comment by Aldo-f** [comment]
What do you want?
I had this issue yesterday...

**Comment by smallp** [comment]
So when will it show the log? This log shows that the extension parses file failed. I need to know what causes the problem.
BTW, you can figure out which class that don't have autocomplete of function. Usually this class causes the problem.

**Comment by Aldo-f** [comment]
```
Debugger listening on ws://127.0.0.1:6011/976e1d2c-929e-472b-b880-9b7c6785e536
For help, see: https://nodejs.org/en/docs/inspector
start small-ci on 17688
read dir fail:d:\Users\ME\Git\SITE/application/models/
[Error - 17:47:50] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'funs' of null
  Code: -32603 
```

CodeIgniter is installed under ``/app`` (instead of `/application` )
Which would fix the first error: `read dir fail:`

**Comment by smallp** [comment]
Check your setting first. Have you set the setting `CI.app` to app?
