### ISSUE TITLE
This extension was broken with the new VScode update

### ISSUE THREAD

**Issue by cuyaguerofajardo** [smallp/vscode-ci#65]
I run the command: refresh Model. I received this message: 'extension.refreshModel' not found

**Comment by smallp** [comment]
In vscode  1.63.0?

**Comment by cuyaguerofajardo** [comment]
If I remember correctly, it stopped working with the November update, currently not working

**Comment by smallp** [comment]
I see. I'll check it.

**Comment by smallp** [comment]
It work fine for me in 1.63.0. So have you change the name of system? And check the output, is there a `small-ci` select?
BTW, this one cannot run in untrusted workspace. I believe this is the reason.

**Comment by cuyaguerofajardo** [comment]
ok, I'll check it and I'll be letting you know

**Comment by cuyaguerofajardo** [comment]
Solved, that was the problem, thanks
