### ISSUE TITLE
Open Multiple CI Code Objects in One workspace issue

### ISSUE THREAD

**Issue by gitHusband** [smallp/vscode-ci#66]
If I open More Than one CI code Object in One workspace, 
vscode-ci does not work.

`
Object1
 - docroot
 - logs
 - src
   - application
   - system

Object2
 - docroot
 - logs
 - src
   - application
   - system

Object3
 - application
 - system
`
Could you please make them all work? Thanks!

**Comment by smallp** [comment]
你是说一个工作空间有多个文件夹，一个文件夹是一个项目？这个我根据文档做过处理，不过没测试过……你要是有空的话可以试试调试一下，提个PR什么的，我现在不做PHP了。

**Comment by gitHusband** [comment]
> 你是说一个工作空间有多个文件夹，一个文件夹是一个项目？这个我根据文档做过处理，不过没测试过……你要是有空的话可以试试调试一下，提个PR什么的，我现在不做PHP了。

是的，一个空间多个项目。

好吧，我没试过写vscode 的插件。以后有时间我试试，谢谢。
