### ISSUE TITLE
Model regcognition is broken with PHP Intelephense 1.9

### ISSUE THREAD

**Issue by brainsap-gmbh** [smallp/vscode-ci#73]
Hello,

Thanks for this wonderful addon. Its working very well.

However with the new PHP Intelephense 1.9 the Models show error on a controller level.

See Screenshot:

![grafik](https://user-images.githubusercontent.com/116944889/210317296-48c839f3-bb7e-4be4-ba86-31727d258578.png)

If I revert to PHP Intelephense 1.8.2 it works fine:

![grafik](https://user-images.githubusercontent.com/116944889/210317475-ed626924-a604-4383-b36d-24bf6fb7557d.png)

Not sure if this is an issue with PHP Intelephense or the CI-Extension

**Comment by smallp** [comment]
That's because PHP Intelephense cannot regcognition the variable. The jump function of my extension should work fine, and it means the extension is fine.
BTW, you can add definition of the variable to the class to remove the warning.
