### ISSUE TITLE
This extension overwrites right rule to wrong rule.

### ISSUE THREAD

**Issue by changgyu78** [smallp/vscode-ci#78]
Inside <script> ... </script> tag of HTML file, changing code to comment action goes wrong.

for example.
commenting expected and as origin vscode be:
`console.log(" ");`  ==[ Ctrl+/ ]==>  `// console.log(" ");`

but, with this plug-in activated: 
`console.log(" ");`  ==[ Ctrl+/ ]==>   `<!-- console.log(" "); -->`

originally, vscode can distinguish, Inside/outside of `<script> ... </script>`.

**Comment by smallp** [comment]
That's strange. This extention do not change the way comment. Can you show a small repo to reproduce this issue?
