### ISSUE TITLE
How come it seems like the intellisense check isn't working?

### ISSUE THREAD

**Issue by xxdyu** [smallp/vscode-ci#79]
![image](https://github.com/smallp/vscode-ci/assets/32918557/c40ee5e9-8fda-438d-b6b5-bba1bd33bffd)

**Comment by smallp** [comment]
You can try to run CI: refresh Model command to figure out if this extension starts.

**Comment by xxdyu** [comment]
![image](https://github.com/smallp/vscode-ci/assets/32918557/c67b0498-a3fe-44d1-8501-04ff0c2552a7)

**Comment by smallp** [comment]
插件没启用，你看看你的system文件夹是不是改名字了，改名字了要改配置

**Comment by xxdyu** [comment]
thanks
