### ISSUE TITLE
Name: [Deprecated] Bracket Pair Colorizer 2 Id: CoenraadS.bracket-pair-colorizer-2 Description: A customizable extension for colorizing matching brackets Version: 0.2.4 Publisher: CoenraadS VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

### ISSUE THREAD

**Issue by aabdoaa** [smallp/vscode-ci#81]
Name: [Deprecated] Bracket Pair Colorizer 2
Id: CoenraadS.bracket-pair-colorizer-2
Description: A customizable extension for colorizing matching brackets
Version: 0.2.4
Publisher: CoenraadS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

**Comment by aabdoaa** [comment]
Name: [Deprecated] Bracket Pair Colorizer 2
Id: CoenraadS.bracket-pair-colorizer-2
Description: A customizable extension for colorizing matching brackets
Version: 0.2.4
Publisher: CoenraadS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

**Comment by smallp** [comment]
I believe you create issue in a wrong repo.
