### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vicky4165** [smallp/vscode-ci#83]
- Issue Type: `Performance`
- Extension Name: `php-ci`
- Extension Version: `0.4.2`
- OS Version: `Linux x64 5.15.0-102-generic`
- VS Code version: `1.70.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/small.php-ci-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smallp** [comment]
It will causes high cpu load if your project is so big. But after it has searched the model files, it would become idle.
